### ISSUE TITLE
synth-designer submodule at assets/vendor/bleep-synth is not public

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [samaaron/bleep#24]
Hey Sam,

I noticed you made this repository public.

However the git submodule at `assets/vendor/bleep-synth` at https://github.com/samaaron/synth-designer.git is still private. The project cannot be built without it. Mix returns:

`Failed to copy assets/vendor/bleep-synth/bleepsynth/server-assets: enoent`

**Comment by samaaron** [comment]
yep, I'm aware, but I can't make the submodule public until the parent repo is too. I'm waiting on @guyjbrown to enable this :-)

**Comment by samaaron** [comment]
It's now public :-)
